"""
generate_report.py — Generate a consolidated Markdown report from extraction results.

Pipeline v2:
  - main_ideas:        extracted by LangExtract (Aha! moments + parent-child structure)
  - social_media:      generated by Gemini from ideas (list of 'post' entities)
  - teaching_material: generated by Gemini from ideas (list of 'lecture_note' entities)
"""

import json
import os
from pathlib import Path


def _load_jsonl(filepath: str) -> list[dict]:
    """Load extractions from a JSONL file."""
    results = []
    if not os.path.exists(filepath):
        return results
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                results.append(json.loads(line))
    return results


def _load_json(filepath: str) -> list:
    """Load a JSON list from a file."""
    if not os.path.exists(filepath):
        return []
    with open(filepath, encoding="utf-8") as f:
        return json.load(f)


def _extract_entities(data: list[dict]) -> list[dict]:
    """Pull out individual extractions from the JSONL annotated-document data."""
    entities = []
    for doc in data:
        for ext in doc.get("extractions", []):
            if ext and ext.get("extraction_text"):
                entities.append(ext)
    return entities


def _attrs(entity: dict) -> dict:
    """Safely get attributes dict, handling None values."""
    return entity.get("attributes", {}) or {}


def generate_report(book_name: str, results_dir: str, output_path: str) -> str:
    """
    Generate a Markdown report from all extraction results.

    Args:
        book_name:   Stem name of the book (without extension).
        results_dir: Directory containing the result files.
        output_path: Path to write the Markdown report.

    Returns:
        The path of the generated report.
    """
    lines = []
    lines.append(f"# 📚 Análisis: {book_name}\n")
    lines.append(f"*Reporte generado automáticamente con LangExtract + Gemini*\n")
    lines.append("---\n")

    # ── SECTION 1: Main Ideas (primary extraction) ──
    _add_main_ideas(lines, book_name, results_dir)

    # ── SECTION 2: Social Media ──
    _add_social_media(lines, book_name, results_dir)

    # ── SECTION 3: Teaching Material / Lecture Notes ──
    _add_teaching_material(lines, book_name, results_dir)

    report_content = "\n".join(lines)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report_content)

    return output_path


def _add_main_ideas(lines: list, book_name: str, results_dir: str):
    """Add main ideas section (LangExtract output with Aha! moments)."""
    filepath = os.path.join(results_dir, f"{book_name}_main_ideas.jsonl")
    entities = _extract_entities(_load_jsonl(filepath))
    if not entities:
        return

    lines.append("## 💡 Ideas Principales — Momentos Aha!\n")

    ideas       = [e for e in entities if e.get("extraction_class") == "main_idea"]
    arguments   = [e for e in entities if e.get("extraction_class") == "argument"]
    conclusions = [e for e in entities if e.get("extraction_class") == "conclusion"]

    if ideas:
        lines.append("### Ideas clave\n")
        for i, idea in enumerate(ideas, 1):
            attrs = _attrs(idea)
            importance  = attrs.get("importance", "")
            imp_icon    = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(importance, "⚪")
            lines.append(f"{i}. {imp_icon} *\"{idea.get('extraction_text', '')}\"*")
            if attrs.get("aha_moment"):
                lines.append(f"   - 💥 **Aha!:** {attrs['aha_moment']}")
            if attrs.get("framework"):
                lines.append(f"   - 🔧 **Framework:** {attrs['framework']}")
        lines.append("")

    if arguments:
        lines.append("### Argumentos de soporte\n")
        for arg in arguments:
            attrs = _attrs(arg)
            lines.append(f"- *\"{arg.get('extraction_text', '')}\"*")
            if attrs.get("aha_moment"):
                lines.append(f"  - 💥 {attrs['aha_moment']}")
            if attrs.get("parent_idea"):
                lines.append(f"  - → Apoya: *{attrs['parent_idea']}*")
        lines.append("")

    if conclusions:
        lines.append("### Conclusiones y takeaways\n")
        for con in conclusions:
            attrs = _attrs(con)
            lines.append(f"> *\"{con.get('extraction_text', '')}\"*")
            if attrs.get("aha_moment"):
                lines.append(f"> 💥 {attrs['aha_moment']}")
        lines.append("")

    lines.append("---\n")


def _add_social_media(lines: list, book_name: str, results_dir: str):
    """
    Add social media section.
    Supports new 'post' format (Gemini-generated) and old 'quote/insight/hook' format.
    """
    # Try new JSON format first
    json_path  = os.path.join(results_dir, f"{book_name}_social_media.json")
    jsonl_path = os.path.join(results_dir, f"{book_name}_social_media.jsonl")

    entities = []
    if os.path.exists(json_path):
        entities = _load_json(json_path)
    else:
        entities = _extract_entities(_load_jsonl(jsonl_path))

    if not entities:
        return

    lines.append("## 📱 Contenido para Redes Sociales\n")
    lines.append("*Generado a partir de las ideas principales del libro*\n")

    posts = [e for e in entities if e.get("extraction_class") == "post"]

    if posts:
        # New format: posts generated from ideas
        lines.append("### 🐦 Posts para X (Twitter)\n")
        for i, post in enumerate(posts, 1):
            tweet = post.get("extraction_text", "")
            attrs = _attrs(post)
            lines.append(f"**Post {i}:**")
            lines.append(f"```\n{tweet}\n```")
            if attrs.get("idea_source"):
                lines.append(f"*Basado en:* {attrs['idea_source']}\n")
            else:
                lines.append("")

        ig_posts = [p for p in posts if _attrs(p).get("instagram_caption")]
        if ig_posts:
            lines.append("### 📸 Captions para Instagram\n")
            for i, post in enumerate(ig_posts, 1):
                caption = _attrs(post).get("instagram_caption", "")
                lines.append(f"**Post {i}:**")
                lines.append(f"```\n{caption}\n```\n")

    else:
        # Legacy format: quote/insight/hook from LangExtract
        quotes   = [e for e in entities if e.get("extraction_class") == "quote"]
        insights = [e for e in entities if e.get("extraction_class") == "insight"]

        if quotes:
            lines.append("### 🐦 Posts para X (Twitter)\n")
            for i, q in enumerate(quotes, 1):
                attrs = _attrs(q)
                tweet = attrs.get("tweet", q.get("extraction_text", ""))
                lines.append(f"**Post {i}:**")
                lines.append(f"```\n{tweet}\n```\n")

        if insights:
            lines.append("### 💎 Insights clave\n")
            for ins in insights:
                attrs = _attrs(ins)
                lines.append(f"- *\"{ins.get('extraction_text', '')}\"*")
                if attrs.get("takeaway"):
                    lines.append(f"  - **Takeaway:** {attrs['takeaway']}")
            lines.append("")

    lines.append("---\n")


def _add_teaching_material(lines: list, book_name: str, results_dir: str):
    """
    Add teaching material / lecture notes section.
    Supports new 'lecture_note' format (Gemini-generated) and old 'concept/definition' format.
    """
    # Try new JSON format first
    json_path  = os.path.join(results_dir, f"{book_name}_teaching_material.json")
    jsonl_path = os.path.join(results_dir, f"{book_name}_teaching_material.jsonl")

    entities = []
    if os.path.exists(json_path):
        entities = _load_json(json_path)
    else:
        entities = _extract_entities(_load_jsonl(jsonl_path))

    if not entities:
        return

    lines.append("## 🎓 Material para Clases — Lecture Notes\n")
    lines.append("*Elaborado a partir de las ideas principales del libro*\n")

    lecture_notes = [e for e in entities if e.get("extraction_class") == "lecture_note"]

    if lecture_notes:
        # New format: lecture notes generated from ideas
        for i, note in enumerate(lecture_notes, 1):
            attrs       = _attrs(note)
            title       = attrs.get("title", f"Lección {i}")
            subtitle    = attrs.get("subtitle", "")
            aha         = attrs.get("aha_moment", "")
            key_point   = note.get("extraction_text", "")
            example     = attrs.get("example", "")

            lines.append(f"### 📖 Lección {i}: {title}")
            if subtitle:
                lines.append(f"*{subtitle}*\n")
            if key_point:
                lines.append(f"**Punto clave del autor:** *\"{key_point}\"*\n")
            if aha:
                lines.append(f"💥 **Momento Aha!:** {aha}\n")
            if example:
                lines.append(f"🔧 **Ejemplo / Framework:** {example}\n")
            lines.append("")

    else:
        # Legacy format: concept/definition/example/discussion_question
        concepts  = [e for e in entities if e.get("extraction_class") == "concept"]
        questions = [e for e in entities if e.get("extraction_class") == "discussion_question"]

        if concepts:
            lines.append("### Conceptos clave\n")
            for c in concepts:
                attrs = _attrs(c)
                lines.append(f"- **{c.get('extraction_text', '')[:80]}**")
                if attrs.get("explanation"):
                    lines.append(f"  - {attrs['explanation']}")
            lines.append("")

        if questions:
            lines.append("### 🤔 Preguntas de discusión\n")
            for i, q in enumerate(questions, 1):
                attrs    = _attrs(q)
                question = attrs.get("suggested_question", q.get("extraction_text", ""))
                lines.append(f"{i}. **{question}**")
            lines.append("")

    lines.append("---\n")


# ── Export extraction data as JSON ────────────────────────────────────────────

def export_ideas_json(book_name: str, results_dir: str, output_path: str) -> str:
    """Export all extraction results as a structured JSON file."""

    def _load_or_entities(json_p: str, jsonl_p: str) -> list:
        if os.path.exists(json_p):
            with open(json_p, encoding="utf-8") as f:
                return json.load(f)
        return _extract_entities(_load_jsonl(jsonl_p))

    data = {
        "book":             book_name,
        "main_ideas":       _extract_entities(_load_jsonl(
                                os.path.join(results_dir, f"{book_name}_main_ideas.jsonl"))),
        "social_media":     _load_or_entities(
                                os.path.join(results_dir, f"{book_name}_social_media.json"),
                                os.path.join(results_dir, f"{book_name}_social_media.jsonl")),
        "teaching_material": _load_or_entities(
                                os.path.join(results_dir, f"{book_name}_teaching_material.json"),
                                os.path.join(results_dir, f"{book_name}_teaching_material.jsonl")),
    }

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    return output_path


# ── Backward-compatible alias ─────────────────────────────────────────────────
export_qa_json = export_ideas_json
